In [1]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [3]:
data_dict = unpickle('./data/data_batch_1')
data = data_dict[b'data']
labels = data_dict[b'labels']
for i in range(2,6):
    data_dict = unpickle('./data/data_batch_'+str(i))
    data = np.concatenate((data, data_dict[b'data']))
    labels = np.concatenate((labels, data_dict[b'labels']))

In [4]:
data=(data[:,0:1024]+data[:,1024:2048]+data[:,2048:3072])/3

In [5]:
classes = []
means = []
for i in range(10):
    classes.append(data[labels==i])
for i in range(10):
    means.append(np.mean(classes[i],0))

In [11]:
emat = np.zeros([10,10])
for i in range(0,10):
    for j in range(i+1,10):
        dist= np.linalg.norm(means[i]-means[j])
        emat[i][j] = emat[j][i] = np.around(dist,2)
#         print("Distance between mean of", i , "and", j, "is", dist)

In [12]:
print(emat)

[[  0.    45.49  49.6   55.35  54.62  64.41  56.16  35.31  36.31  78.61]
 [ 45.49   0.    61.26  70.58  66.4   79.14  69.9   45.63  40.73  59.93]
 [ 49.6   61.26   0.    22.53  16.37  27.22  24.84  33.05  33.45 108.58]
 [ 55.35  70.58  22.53   0.    19.96  20.63  17.55  42.01  45.33 118.36]
 [ 54.62  66.4   16.37  19.96   0.    22.01  21.74  37.97  39.01 114.54]
 [ 64.41  79.14  27.22  20.63  22.01   0.    24.04  47.58  50.5  126.85]
 [ 56.16  69.9   24.84  17.55  21.74  24.04   0.    44.99  47.42 119.64]
 [ 35.31  45.63  33.05  42.01  37.97  47.58  44.99   0.    19.44  83.67]
 [ 36.31  40.73  33.45  45.33  39.01  50.5   47.42  19.44   0.    81.99]
 [ 78.61  59.93 108.58 118.36 114.54 126.85 119.64  83.67  81.99   0.  ]]
